# Generated by Django 5.0.6 on 2024-06-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
